#PBS -N rm_hg38_XY_cy_rep
#PBS -A GT-sy58-biocluster
#PBS -l nodes=1:ppn=1
#PBS -l walltime=4:00:00
#PBS -l mem=10gb
#PBS -o outputs/${IDARG}_hg38_XY_bismark_cy_rep.out
#PBS -j oe
#PBS -m a
#PBS -M rmorgan61@gatech.edu


cd ~/p-sy58-0/remapping/meth_extract/human_XY/

module load python/2.7
module load gcc/10.1.0
module load intel/19.0.5
module load samtools/1.14

echo "Starting cytosine report"

coverage2cytosine -o ${IDARG}_processed_bismark_bt2_pe.deduplicated \
        --dir ./ \
        --genome_folder ~/p-sy58-0/genomes/human_XY/ \
        ./${IDARG}_processed_bismark_bt2_pe.deduplicated.bedgraph.gz.bismark.cov.gz


echo "Complete"
