#PBS -N rm_hg38_XY_dedup
#PBS -A GT-sy58-biocluster
#PBS -l nodes=1:ppn=4
#PBS -l walltime=24:00:00
#PBS -l mem=100gb
#PBS -o outputs/${IDARG}_hg38_XY_bismark_dedup.out
#PBS -j oe
#PBS -m a
#PBS -M rmorgan61@gatech.edu

module load python/2.7
module load gcc/10.1.0
module load intel/19.0.5
module load samtools/1.14

cd ~/p-sy58-0/remapping

echo "Starting hg38 deduplication"
deduplicate_bismark -p --output_dir ./dedup/human_XY --bam ./bs_mapped/human_XY/${IDARG}_processed_bismark_bt2_pe.bam
echo "Complete"
