#PBS -N rm_hg38_XY_2bedGraph
#PBS -A GT-sy58-biocluster
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00:00
#PBS -l mem=16gb
#PBS -o outputs/${IDARG}_hg38_XY_bismark_2bedGraph.out
#PBS -j oe
#PBS -m a
#PBS -M rmorgan61@gatech.edu


cd ~/p-sy58-0/remapping/meth_extract/human_XY

module load python/2.7
module load gcc/10.1.0
module load intel/19.0.5
module load samtools/1.14

echo "Starting 2 bedGraph"

bismark2bedGraph -o ${IDARG}_processed_bismark_bt2_pe.deduplicated.bedgraph.gz \
        --dir ./ \
        --buffer_size 40% \
        ./CpG_context_${IDARG}_processed_bismark_bt2_pe.deduplicated.txt.gz

echo "Complete"
